### ISSUE TITLE
WMIHACKER_0.6.vbs(60, 3) SWbemLocator: 拒绝访问。

### ISSUE THREAD

**Issue by omiter** [360-Linton-Lab/WMIHACKER#2]
cscript //nologo .\WMIHACKER_0.6.vbs /cmd 192.168.211.130 omite "123QWEasd" "ipconfig" 1
![image](https://user-images.githubusercontent.com/30787494/86551085-ae53e000-bf76-11ea-9d2b-8b6672bb5f2d.png)
这个是为什么哇，有老哥遇到吗0.0

**Comment by rootclay** [comment]
第一要确保用户名密码正确。
第二是Windows7这样的客户端版本是需要调整防火墙策略的（为了方便你可以关闭防火墙），Server版本是默认能够直接连接的。

**Comment by omiter** [comment]
> 第一要确保用户名密码正确。
> 第二是Windows7这样的客户端版本是需要调整防火墙策略的（为了方便你可以关闭防火墙），Server版本是默认能够直接连接的。

谢谢，用administrator账户试了试，可以用了~非常感谢

**Comment by rootclay** [comment]
Your Question is：
In a workgroup, the account connecting to the remote computer is a local user on that computer. Even if the account is in the Administrators group, UAC filtering means that a script runs as a standard user.

在工作组中，连接到远程计算机的帐户是该计算机上的本地用户。即使该帐户在Administrators组中，UAC也会以标准用户身份运行。所以会出现拒绝访问。

**Comment by rootclay** [comment]
在域环境中，使用远程计算机的本地Administrators组中的域帐户连接到目标计算机是可以的。

**Comment by omiter** [comment]
好的，回头研究一下代码，谢谢老哥费心指导
