### ISSUE TITLE
How to use this tool ?

### ISSUE THREAD

**Issue by cymilad** [360-Linton-Lab/WMIHACKER#4]
I want to get shell or meterpreter access

**Comment by I-Good-Vegetable** [comment]
Maybe we can try to upload a payload and execute it~

**Comment by rootclay** [comment]
> Maybe we can try to upload a payload and execute it~

Yes, of course, you can execute after uploading the file

**Comment by rootclay** [comment]
> I want to get shell or meterpreter access

You can read the readme file
